[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"

[variables]
NEWS_API_KEY = "7cdbae1ef22b4adda9740958b0383f13"
TWITTER_BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAABVj3AEAAAAAmhiW9ldmhlJ64ANMCoU35THhqBs%3DkgmhbKcZ6ALLft36nJxj0Z6OFLLHjjSFYqrFcABaE2QOk3GTx2"
JWT_SECRET = "simba-watch-secret-key-2024"
MONGO_URL = "${{MongoDB.DATABASE_URL}}"